apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transparent-chart-hosted-repository.fullname" . }}
  labels:
    {{- include "transparent-chart-hosted-repository.labels" . | nindent 4 }}
stringData:
  index.yaml: |
    apiVersion: v1
    entries:
      transparency:
      - apiVersion: v2
        appVersion: 1.0.0
        created: "2024-02-10T05:55:56.227316552Z"
        description: A transprent Helm chart for Kubernetes
        digest: c8cff0d77f98e6e9de2463ea902c0ef1b0e1b8ee4ab69b8b2f07b4f9adfdac89
        name: transparency
        type: application
        urls:
        - https://github.com/iijimakazuyuki/transparency/releases/download/transparency-1.0.0/transparency-1.0.0.tgz
        version: 1.0.0
    generated: "2024-02-10T05:55:56.22734232Z"
data:
  transparency-1.0.0.tgz: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOxWTYvbPBDO2b9i0Psea1t2Yht8K70U2kNPC2XZw6w93mjxhypNAiHNfy+ysyYxLYE2ZFnWz0X2aEYzkuYZDRtsrUZDbbELP63RcLDDpl5cE1JKma5W/SilnI4yjqJFtErSKJVZliwXMlpmUbwAedUo/oCNZTQL+c++ppt7I0Ct7shY1bU5bGMPtR5/o0AG0ivJFkZp7kUfYcgXQy3DZ6obKFzKQNUZ+LJ5JNMSk/VabCiH09TyeKcpB9S6VgW6xbztuZ/XPoh3ijP+b7HekL16AbjEfxmlE/6vomQ58/8WaLBVFVm2Odw/zCR8d/gd/22xpgaDZ9u1V/Fxif9JHE/4n6zimf83wd4DEP8PNy5yEGtmbfMwdJfvHxOhM09habBiX2bhIPtPfHCGWJbKPeZYfzOdJsOKrMihwtpSr6BPxc4XgBhLzigCECdthgvjq7IMXQUvulCpmnqfvbZiak7NAYRrMJxl9/hMBYvjxGE0eZlHY3A3TB+8o4Iw9GOjDJUih/tpkB7AQ6/Eiut+ibueJsMJTN0e3lgNPeM/U6NrZLLhuP1rNAMX3/8sm/A/TZO5/78J9nsfDLZPBMGQ1sF49XA4eL7ve/s9BPATuPuOTe2Ezoba0n2+dvgzZsyYMeMv8SsAAP//BbEu/AAUAAA=
